urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from archfinch.links.feeds import LinkFeed


urlpatterns = patterns('',
    url(r'^$',     'archfinch.main.views.recommend', {'category_slug': 'fresh'}, name='frontpage'),
    url(r'^missing$', 'archfinch.main.views.missing', name='missing'),
    url(r'^submit$', 'archfinch.links.views.submit', name='submit'),

    url(r'^similar$', 'archfinch.users.views.similar', name='similar'),
    url(r'^similar/(?P<page>\d+)$', 'archfinch.users.views.similar', name='similar-paged'),
    url(r'^recommend/fresh$', 'archfinch.main.views.recommend', {'category_slug': 'fresh'}, name='fresh'),
    url(r'^recommend$', 'archfinch.main.views.recommend', name='recommend'),
    url(r'^recommend/(?P<category_slug>[a-z-]+)$', 'archfinch.main.views.recommend', name='recommend-slugged'),
    url(r'^recommend/before/(?P<before>[0-9a-z]{1,13})(?P<json>\.json)?$', 'archfinch.main.views.recommend', name='recommend-paged'),
    url(r'^recommend/(?P<category_slug>[a-z-]+)/(?P<before>[0-9a-z]{1,13})(?P<json>\.json)?$', 'archfinch.main.views.recommend', name='recommend-slugged-paged'),
    url(r'^recommend(?:/(?P<category_slug>[a-z-]*))?/for/(?P<usernames>[,\w@\+\.-]+)(?:/(?P<before>[0-9a-z]{1,13}))?(?P<json>\.json)?$', 'archfinch.main.views.recommend', name='recommend-for'),

    url(r'task_wait/(?P<task_id>[\w-]+)$', 'archfinch.main.views.task_wait', name='task-wait'),
    url(r'task_wait_error$', 'archfinch.main.views.task_wait_error', name='task-wait-error'),
    
    (r'^account/', include('archfinch.account.urls')),
    (r'^wiki/', include('archfinch.wiki.urls')),
    (r'^comment/', include('archfinch.comments.urls')),
    (r'^user/', include('archfinch.users.urls')),
    url(r'^me$', 'archfinch.users.views.overview_me', name='user-overview-me'),
    (r'^list/', include('archfinch.lists.urls')),
    (r'^convert/', include('lazysignup.urls')),

    url(r'^topusers$', 'archfinch.users.views.top_users', name='top-users'),

    url(r'^lists$', 'archfinch.lists.views.overview', name='lists-overview'),
    url(r'^lists/user/(?P<username>[\w@\+\.-]+)$', 'archfinch.lists.views.user', name='lists-user'),
    url(r'^utils/markdown$', 'archfinch.main.views.process_markdown', name='utils-markdown'),

    url(r'^item/(?P<item_id>[0-9a-z]{1,13})(?:/(.*))?$', 'archfinch.main.views.item', name='item'),
    (r'^also_liked/(?P<item_id>[0-9a-z]{1,13})/(?P<like>true|false)/(?P<also_like>true|false)$', 'archfinch.main.views.item_also_liked'),
    (r'^opinion/set/(?P<item_id>[0-9a-z]{1,13})/(?P<rating>[1-5])$', 'archfinch.main.views.opinion_set'),
    (r'^opinion/remove/(?P<item_id>[0-9a-z]{1,13})$', 'archfinch.main.views.opinion_remove'),

    url(r'^rss/followed/(?P<feed_username>[\w@\+\.-]+)$', LinkFeed(), {'followed': True}),
    url(r'^followed(?:/(?P<before>[0-9a-z]{1,13}))?(?P<json>\.json)?$', 'archfinch.main.views.recommend', {'followed': True}, name='followed'),
    url(r'^tags/(?P<tag_names>.+)/before/(?P<before>[0-9a-z]{1,13})(?P<json>\.json)?$', 'archfinch.main.views.recommend', name='fresh-tags-paged'),
    url(r'^rss/tags/(?P<tag_names>.+)', LinkFeed(), name='fresh-tags-rss'),
    url(r'^tags/(?P<tag_names>.+)', 'archfinch.main.views.recommend', name='fresh-tags'),
    url(r'^tag/(?P<tag_names>.+)', 'archfinch.main.views.recommend'),
    (r'^addtag/(?P<item_id>[0-9a-z]{1,13})$', 'archfinch.main.views.add_tag'),
    url(r'^tagaction/(?P<tag_name>[^\/]+)$', 'archfinch.main.views.tag_action', name='tag-action'),
    url(r'^explore/tags$', 'archfinch.main.views.explore_tags', name='explore-tags'),

    url(r'^search$', 'archfinch.search.views.query', {'query': ''}, name='search-base'),
    url(r'^search/(?P<query>.*?)(?:/(?P<page>\d+))?(?P<json>\.json)?(?P<autocomplete>\.autocomplete)?$', 'archfinch.search.views.query', name='search'),
    url(r'^usersearch$', 'archfinch.search.views.user_search', name='user-search'),
    url(r'^tagsearch$', 'archfinch.search.views.tag_search', name='tag-search'),

    url(r'^ref/(?P<username>[\w@\+\.-]+)$', 'archfinch.users.views.referral', name='referral'),

    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/var/django/archfinch/media'}),
        (r'^favicon.ico$', 'django.views.generic.simple.redirect_to', {'url': '/var/django/archfinch/media/favicon.ico', 'permanent': False}),
    )
else:
    urlpatterns += patterns('',
        (r'^sentry/', include('sentry.web.urls')),
    )

sync/models.py
from django.db import models
from django.db.models.signals import post_save
from archfinch.users.models import User


class Source(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return 'Sync source (%s)' % (self.name,)


class Synced(models.Model):
    link = models.ForeignKey('links.Link')
    source = models.ForeignKey(Source)

    original_id = models.CharField(max_length=200, db_index=True)

    scraped = models.BooleanField(default=False, db_index=True)
    scrape_attempts = models.IntegerField(default=0)

    def __unicode__(self):
        return 'Synced #%s from %s' % (self.original_id, self.source.name)


def automatic_tags(sender, **kwargs):
    instance = kwargs['instance']
    archfinch_user = User.objects.get(username='archfinch')

    link = instance.link
    if '(YC' in link.name:
        link.add_tag('ycstartup', archfinch_user)

post_save.connect(automatic_tags, Synced)

main/views.py
from django.shortcuts import get_object_or_404, HttpResponse, HttpResponseRedirect, redirect
from django.template import RequestContext
from django.utils import simplejson
from django.utils.http import base36_to_int, int_to_base36
from django.template.defaultfilters import slugify
from django.template.loader import render_to_string
from django.db.models import Count
from archfinch.main.models import Item, Opinion, Action, Similarity, Category, Tag, TagBlock, TagFollow
from archfinch.main.forms import AddItemForm1, AddItemForm2, AddItemWizard
from archfinch.comments.models import AddCommentForm
from archfinch.users.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.markup.templatetags.markup import markdown
from django.views.decorators.csrf import csrf_exempt
from archfinch.utils import render_to_response
from archfinch.utils.cache import publish_static
from archfinch.main import tasks
import celery.result
from django.core.cache import cache
from lazysignup.decorators import allow_lazy_user
from django.conf import settings
from archfinch.utils import paginate
import time
from datetime import datetime


@allow_lazy_user
def missing(request):
    wiz = AddItemWizard([AddItemForm1, AddItemForm2])
    return wiz(request, model=Item)


@publish_static
def item(request, item_id, publish=False):
    '''
    Item page.
    '''

    from django.contrib.sites.models import Site
    current_site = Site.objects.get_current()

    item_id = base36_to_int(item_id)
    item = get_object_or_404(Item.objects.select_related('category', 'profile'), pk=item_id)

    title = item.__unicode__()

    if item.is_comment():
        # item is a comment, so let's show its root and highlight it instead
        from django.utils.html import strip_tags
        from django.contrib.markup.templatetags.markup import markdown

        root = item.root()
        selected_path = root.path
        item, selected_comment_id = root, item.id

        title = strip_tags(markdown(title))

    else:
        selected_path = None

    add_comment_form = AddCommentForm()

    comment_tree = item.comment_tree(selected_path=selected_path, user=request.user)
    if item.category_id == 8:
        return redirect(reverse('list-view', args=[int_to_base36(item_id), slugify(item.name)]))

    if request.user.is_authenticated():
        also_liked = item.also_liked(user=request.user)
        try:
            opinion = request.user.opinion_set.get(item=item)
        except Opinion.DoesNotExist:
            opinion = None
            recommendation = item.recommendation(request.user)
    else:
        opinion = None
        also_liked = item.also_liked()

    response = render_to_response("main/item.html", locals(), context_instance=RequestContext(request))
    response.publish_static = True
    return response


def item_also_liked(request, item_id, like, also_like):
    '''
    "People who (dis)like x also (dis)like ys".
    '''

    item_id = base36_to_int(item_id)
    item = get_object_or_404(Item, pk=item_id)
    like = like == 'true'
    also_like = also_like == 'true'

    result_html = render_to_string('includes/also_liked.html', {'items': item.also_liked(like=like, also_like=also_like)}, context_instance=RequestContext(request))

    json = simplejson.dumps({'success': True, 'items': result_html})
    return HttpResponse(json, mimetype='application/json')


@publish_static
def recommend(request, followed=False, category_slug=None, before=None, usernames=None, tag_names=None, publish=False, json=False, feed=False, feed_username=None):
    '''
    Shows a list of recommendations.
    '''
    if before is not None:
        before = base36_to_int(before)
     
    fresh = False
    tags = None
    new = False
    if tag_names:
        fresh = True
        category = None
        tag_names = tag_names.split('/')
        tags = Tag.objects.filter(name__in=tag_names)
        selected_tags = tag_names

    elif category_slug is not None and category_slug:
        if category_slug == 'fresh':
            fresh = True
            category = None
        elif category_slug == 'new':
            fresh = True
            category = None
            new = True
        else:
            category = Category.objects.get(slug=category_slug)
    elif followed:
        fresh = True
        category = None
    else:
        category = None

    if not tag_names:
        tag_names = []
    if tag_names:
        tag_names_k = ','.join(tag_names)
    else:
        tag_names_k = ''

    if not followed:
        related_cache_key = 'related_tags;%s' % (tag_names_k,)
        related_cache_key = related_cache_key.replace(' ', '_space_')
        cached_value = cache.get(related_cache_key)
        if cached_value:
            related_tags = cached_value
        else:
            related_tags = list(Tag.objects.related_tags(tags))
            cache.set(related_cache_key, related_tags, 60*60*6)

    n = 50
    if category and category.name in ('Videos', 'Pics') or fresh:
        n = 20

    if usernames is not None:
        usernames = usernames.split(',')
        users = list(map(lambda un: get_object_or_404(User, username=un), usernames))
        usernames_specified = True

    elif feed_username is not None:
        usernames = [feed_username]
        users = [get_object_or_404(User, username=feed_username)]
        usernames_specified = False

    else:
        usernames = [request.user.username]
        users = [request.user]
        usernames_specified = False


    if followed and (users[0].is_anonymous() or not users[0].tagfollow_set.exists() or (request.user.is_anonymous() and not feed_username)):
        recommendations = []
        if feed:
            return locals()
        return render_to_response('main/followed_anonymous.html', locals(), context_instance=RequestContext(request))

    user_ids = map(lambda u: u.id, users)
    usernames_k = '+'.join(sorted(set(map(str, user_ids))))
    usernames_joined = ','.join(usernames)

    try:
        opinion_count = users[0].__class__.objects.filter(pk__in=user_ids).aggregate(Count('opinion'))['opinion__count']
        if opinion_count < 10:
            generic = True
        else:
            generic = False
    except AttributeError:
        generic = True

    if followed:
        generic = False

    if fresh and request.user.is_authenticated():
        generic = False

    if generic:
        usernames_k = '#generic'

    cache_key = 'recommend;%s;%s;%s;%s;%s' % (usernames_k, category_slug, tag_names_k, before, followed)
    cache_key = cache_key.replace(' ', '_space_')
    if settings.DEBUG:
        cache_timeout = 30
    else:
        cache_timeout = 15*60

    cached_value = cache.get(cache_key)

    if category is not None and category.id in (9,10,11) or fresh:
        computed = True
        from archfinch.links.models import Link
        if generic:
            recommendations = Link.objects.recommended_generic(category=category, tags=tags, new=new)
        else:
            recommendations = Link.objects.recommended(users[0], category=category, tags=tags, followed=followed, new=new)

    else:
        if before:
            start = before
        else:
            start = 0

        computed = False
        if cached_value is not None:
            if type(cached_value) == tuple and cached_value[0] == 'task':
                task_id = cached_value[1]
                recommendations = celery.result.AsyncResult(task_id)
            else:
                recommendations = cached_value
                computed = True

        else:
            if generic:
                recommendations = tasks.recommend_generic.delay(category, start)
            else:
                recommendations = tasks.recommend.delay(category, start, users)
            task_id = recommendations.task_id
            cache.set(cache_key, ('task', task_id), cache_timeout)

        if not computed and recommendations.ready():
            recommendations = recommendations.result
            cache.set(cache_key, recommendations, cache_timeout)
            computed = True

        if not computed and (publish or json):
            recommendations = recommendations.get()
            cache.set(cache_key, recommendations, cache_timeout)
            computed = True

    if not computed:
        wait_page = 'recommend'
        return render_to_response("main/wait.html", locals(), context_instance=RequestContext(request))
    else:
        if json:
            ext = 'json'
        else:
            ext = 'html'
        if category is not None and category.id in (9,10,11) or fresh:
            # links
            if before:
                before = datetime.fromtimestamp(before)
            else:
                before = datetime.now()
            recommendations = recommendations.timeslice(before=before, n=n)
            if len(recommendations) > n:
                next_before = int(time.mktime(recommendations[n].time.timetuple()))
                recommendations = recommendations[:n]

            if feed:
                return locals()
            response = render_to_response("links/recommend.%s" % (ext,), locals(), context_instance=RequestContext(request))
        else:
            if len(recommendations) > n:
                next_before = start+n
                recommendations = recommendations[:n]

            if request.user.is_authenticated():
                user_categories = request.user.categories()
                categories = Category.objects.filter(hide=False).order_by('name').values_list('id', 'element_plural', 'slug')
            response = render_to_response("main/recommend.%s" % (ext,), locals(), context_instance=RequestContext(request))

        if json:
            json_data = simplejson.dumps(response.content)
            return HttpResponse(json_data, mimetype='application/json')
        if not tags or 'hn' in tag_names:

templates/main/additem.html
{% extends "base.html" %}

{% load base36 %}

{% block content_left %}
<h1>{% if model == 'Link' %}Submit a link{% else %}What are we missing?{% endif %}</h1>
<div class="big">
    {% if step == 1 %}
        {% if model == 'Item' %}
            <p>Hint: make sure the title is canonical. You can do that by checking the title on Wikipedia, IMDb, etc.</p>
            <p>For example, The <em>Godfather Part II</em> is preferable to <em>Godfather 2</em> or the <em>god father part ii</em>.</p>
        {% endif %}
    {% else %}
        <p>The thing you are trying to add might already be in the database. The candidates are:
        {% for item in potential_conflicts %}
        <div class="title"><a href="{{ item.get_absolute_url }}">{{ item }}</a></div>
        {% endfor %}
        <p>Are you sure it's not one of them?</p>
    {% endif %}
    <form method="post">{% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
        {{ previous_fields|safe }}
        <br />
        <input type="submit" value="{% if step == 1 %}Submit{% else %}I'm sure{% endif %}">
    </form>
</div>
{% if model == 'Link' %}
<br><br>
<h4>Guidelines</h4>
<p><b>What should I submit?</b>
</p>
<p>Anything that makes you go "Wow, that is really _____", where _____ is any of the following: thought-provoking, interesting, cool, insightful, awesome, beautiful, informative.</p><p>You should avoid submitting seemingly interesting but shallow topics, such as celebrity gossip or disaster news, as they push off the more interesting and profound but less flashy things, thus reducing the average quality.</p>
<p><b>Things to keep in mind</b></p>
<p>Don't sensationalize submissions. If the original title is terrible, try to edit your own one.</p>
<p>Always try to link to the original source.</p>
<p><b>Thanks</b></p>
<p>Thank you for submitting and reading this far. You're making Archfinch a better place for everyone.</p>
{% endif %}
{% endblock %}

templates/main/explore_tags.html
{% extends base %}

{% block title %}
Explore tags - Archfinch
{% endblock %}

{% block media %}
{% include "includes/generate_lists_tip.html" %}
{% endblock %}

{% block content_left %}
<h1>Explore tags</h1>

<div class='tag-explorer'>
    <div class='tagfilter-container'><input type='text' id='tagfilter'></div>
    {% for tag in popular_tags %}
        <div class='tag-cell' tag='{{ tag.name }}'>
            <span class="tag"><a class="taglink" href="{% url fresh-tags tag.name %}" tag_name="{{ tag.name }}">{{ tag.name }}</a></span> <span style='font-size: 10px'>{{ tag.count }}</span>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/main/followed_anonymous.html
{% extends base %}

{% block content_left %}

<h1>I have a bad feeling about this</h1>

<p>You don't follow anything.</p>

<p>You should start though, so <a href="{% url explore-tags %}">explore some tags »</a></p>

{% endblock %}

templates/main/item.html
{% extends base %}

{% load markup %}
{% load base36 %}
{% load cache %}

{% block title %}
{{ title }} - Archfinch
{% endblock %}

{% block media %}
    <!--[if IE]><script language="javascript" type="text/javascript" src="/media/js/lib/flot/excanvas.min.js"></script><![endif]-->
    <script type="text/javascript" src="/media/js/lib/flot/jquery.flot.min.js"></script>

{% if not item.is_link and not item.is_comment %}
    <script type="text/javascript">
    $(document).ready(function(){
        $.plot($("#ratings_graph"), [
            {
                data: [
                {% cache 86400 ratings_count item.id %}
                {% for rating, count in item.ratings_count %}
                    [{{ rating }}, {{ count }}]{% if not forloop.last %},{% endif %}
                {% endfor %}
                {% endcache %}
                ],
                bars: {show: true, barWidth: 0.75, align: "center", fill: 0.5},
                color: 1
            }
        ],
        {
            grid: {tickColor: "transparent", hoverable: true},
            yaxis: {ticks: [], autoscaleMargin: 0.1},
            xaxis: {autoscaleMargin: 0.05, ticks: [1,2,3,4,5]}
        });
    });
    </script>
{% endif %}

{% include "includes/generate_lists_tip.html" %}
{% endblock %}

{% block content_left %}
<h1>{{ item.name }}</h1>
{% if item.is_comment %}
{% else %}
    {% include "includes/opinionbox.html" with page_id="item" item=item item_id=item.id yr_big=1 terse_layout=1 item_name=item.name category_singular=item.category.element_singular seq_term=1 your_rating=opinion.rating link=item.link %}
{% endif %}

{% if not item.is_comment %}
    {% if item.profile.page %}
        <div class="article">
        {{ item.profile.page.render|markdown }}
        </div>
        <span class="smalltext"><p>(<a href='{% url wiki-edit-item item.id|base36 %}'>edit</a>)</p></span>
    {% else %}
        <p>There is no information on this {{ item.category.element_singular }}. <a href='{% url wiki-edit-item item.id|base36 %}'>Add some.</a></p>
    {% endif %}
{% endif %}

<h3>Comments</h3>

{% include "includes/add_comment_form.html" with parent_id=item.id %}

<br /><br />

{% include "includes/comment_tree.html" with comment_tree=comment_tree %}


{% with similar_items=item.similar_by_tags %}
    {% if similar_items %}
        <br /><br />
        <h4>Similar</h4>
        <div class="similar">
        {% for similar_item in similar_items %}
            {% include "includes/opinionbox.html" with item=similar_item selected_tags=item.popular_tags_names page_id="similar_by_tags" item_id=similar_item.id yr_big=1 terse_layout=1 item_name=similar_item your_rating=similar_item.rating seq_term=forloop.counter %}
        {% endfor %}
        </div>
    {% endif %}
{% endwith %}

<h4>People who
<button class="also_liked" like_type='like'><span class="like_dislike">like</span> <img src="/media/images/arrow-s.gif" style='padding: 2px; margin-left: -3px;'></button>
{% if item.link or item.is_comment %}
    this {{ item.category.element_singular }}
{% else %}
 {{ item.name }}
{% endif %}
<span id="also_liked_also">also</span>
<button class="also_liked" like_type='also_like'><span class="like_dislike">like</span> <img src="/media/images/arrow-s.gif" style='padding: 2px; margin-left: -3px;'></button>
<img src="/media/images/ajax-loader.gif" style='margin-left: 20px' class="loading nodisplay" id="ld_also_liked">
</h4>
<div id="also_liked_error" class="error"></div>
<div id="item" item_id="{{ item.id|base36 }}"></div>

<div class="also_liked">
{% include "includes/also_liked.html" with items=also_liked %}
</div>


{% endblock %}
{% block content_right %}

{% if not item.is_link and not item.is_comment %}
<div id="ratings_graph"></div>
{% endif %}

{% if item.submitter_show %}
<p>
Submitted by <a href="{% url user-overview item.submitter_show.username %}">{{ item.submitter_show }}</a>
</p>
{% endif %}

{% for sync in item.link.synced_set.all %}
    {% if sync.source.name == 'Hacker News' %}
        <p>Via <a href="http://news.ycombinator.com/item?id={{ sync.original_id }}">HN</a></p>
    {% endif %}
{% endfor %}

<p>Short url: <input type='text' class='short_url' readonly='readonly' value='http://arfn.ch/{{ item.id|base36 }}'></p>

{% endblock %}

{% block ads %}
{% if user.is_anonymous and request.search_referrer_engine %}
    <div id="ads">
        <script type="text/javascript"><!--
        amazon_ad_tag = "archfinch-20"; amazon_ad_width = "180"; amazon_ad_height = "150"; amazon_ad_link_target = "new"; amazon_color_border = "FFFFFF"; amazon_color_link = "0E8D94"; amazon_color_price = "FFAB07"; amazon_color_logo = "FFAB07";//--></script>
        <script type="text/javascript" src="http://www.assoc-amazon.com/s/ads.js"></script>
    </div>
{% endif %}
{% endblock %}

templates/main/recommend.html
{% extends base %}

{% load base36 %}
{% load nbsp %}
{% load sequence %}
{% load reversetag %}

{% block title %}
    {% if category %}
        {{ category.element_singular|capfirst }} recommendations - Archfinch
    {% else %}
        Recommendations - Archfinch
    {% endif %}
{% endblock %}

{% block content_left %}

<h1>
{% if category %}
    {{ category.element_plural|capfirst }}
{% else %}
    Things
{% endif %}
{% if usernames_specified %}
    {{ usernames|sequence }}
{% else %}
    you
{% endif %}
 might like.
</h1>

{% for item in recommendations %}
    {% include "includes/opinionbox.html" with page_id="recommend" item=item item_id=item.id yr_big=1 terse_layout=1 click_hides=1 item_name=item category_singular=item.category_element seq_term=forloop.counter seq_term2=item.id %}
{% empty %}
    {% if not category %}
        <div class="big">
            <p>We don't know {% if usernames_specified %}them{% else %}you{% endif %} well enough to recommend you anything.
            {% if not usernames_specified %}
            <p>We would like to, though, so please consider rating more stuff.</p>
            {% endif %}
        </div>
    {% endif %}
{% endfor %}

{% if usernames_specified %}
    {% reverse partial "recommend-for" category_slug=category_slug|default:"" usernames=usernames_joined as pagination_url %}
{% else %}
    {% if category_slug %}
        {% reverse partial "recommend-slugged-paged" category_slug=category_slug as pagination_url %}
    {% else %}
        {% reverse partial "recommend-paged" as pagination_url %}
    {% endif %}
{% endif %}
{% include "includes/pagination.html" %}

{% endblock %}
{% block content_right %}
{% if user.categories %}
    <p id="user_cats">Show  
    {% for category in user.categories %}
        {% if usernames_specified %}
            {% url recommend-for category.slug|urlencode usernames|join:"," as category_url %}
        {% else %}
            {% url recommend-slugged category.slug|urlencode as category_url %}
        {% endif %}
        <a href='{{ category_url }}'>{{ category.element_plural|nbsp }}</a>{{ forloop.last|yesno:"...,&#44;"|safe}}
    {% endfor %}
    (<a href="#" id="user_cats_more">more</a>)
    </p>

    <p id="global_cats">Show 
    {% for id, repr, slug in categories %}
        {% if usernames_specified %}
            {% url recommend-for slug|urlencode usernames|join:"," as category_url %}
        {% else %}
            {% url recommend-slugged slug|urlencode as category_url %}
        {% endif %}

        {{ forloop.last|yesno:"or ," }}<a href='{{ category_url }}'>{{ repr|nbsp }}</a>{{ forloop.last|yesno:".,&#44;"|safe}}
    {% endfor %}
    </p>

    <br />


{% endif %}

    <p>
        {% if users|length > 1 %}
        Want to add someone else?<br />
        {% else %}
        Watching a movie with someone?<br />
        {% endif %}
        <input type='text' class="search" style='margin: 8px 0 8px 0' id='users_autocomplete' url='{% url recommend-for usernames=",,," %}' usernames='{{ usernames|join:"," }}'> <br />
        {% if users|length <= 1 %}
        Type in their username to include them in your recommendations.
        {% endif %}
    </p>
{% endblock %}
{% block media %}
{% include "includes/generate_lists_tip.html" %}
{% endblock %}

templates/main/recommend_anonymous.html
{% extends base %}

{% block content_left %}

We can't recommend you anything, we don't know you!

<p>We would love to, though, so please <a href="/">sign up</a>!</p>

{% endblock %}

templates/main/wait.html
{% extends base %}

{% block content_left %}

<div style='text-align: center' class='big'>
<p>Hang in there.</p>
<p><img src="/media/images/wait.gif"></p>
<p>
{% if wait_page == 'recommend' %}
We are computing your recommendations as fast as we can.
{% endif %}
</p>
</div>
<div id="wait_error" class="error"></div>

<script type="text/javascript">
$(document).ready(function(){
    task_wait("{{ task_id }}");
});
</script>

{% endblock %}

templates/main/welcome_anonymous.html
{% extends base %}

{% block content_left %}

<div class="big">
    <div class="left">
        Rate things you love or hate. <br />
        Get recommendations based on what <i>you</i> like.
    </div>

    <div class="right">
        Create an account <br /><br />

        <form method="post" id="signupform" action="{% url signup %}">
        <table>
            <tr>
            <td><label for="id_username">Username:</label></td>
            <td><input id="id_username" type="text" name="username" maxlength="30" /></td>
            </tr>
            <tr> 
            <td><label for="id_password">Password:</label></td>
            <td><input type="password" name="password" id="id_password" /></td>
            </tr>
        </table><br />
        {% csrf_token %}
        <input type="submit" value="Create an account" >
        <img src="/media/images/ajax-loader.gif" class="nodisplay loading">
        <div id="signupform_error" class="error"></div>
        </form>
        <div id="signupform_thankyou" class="nodisplay">
            Thank you for signing up. You will be logged in shortly.
        </div>
    </div>
</div>

{% endblock %}